### ISSUE TITLE
MO2 support?

### ISSUE THREAD

**Issue by spannerman79** [rockerbacon/lutris-skyrimse-installers#11]
Hi,
I originally found your post over at [reddit](https://www.reddit.com/r/linux_gaming/comments/cibdb8/any_guides_for_running_skyrim_with_mods_using/ev4orqs/) but I see that you only mention Vortex.  Curious - why don't you support [ModOrganiser 2](https://github.com/ModOrganizer2/modorganizer)?

**Comment by rockerbacon** [comment]
Mod Organizer uses a virtual filesystem feature from Windows that's not supported by Wine (at least it wasn't when I started this, not sure if anything changed).

**Comment by spannerman79** [comment]
Its been patched correctly - see https://www.reddit.com/r/linux_gaming/comments/d3493y/i_got_mod_organizer_2s_usvfs_running_under_wine/

**Comment by rockerbacon** [comment]
That's great news. I expect that the current installer setup for Vortex is more than enough to get MO2 working as well.

The first step would be to swap the .exe Vortex installer with the MO2 installer, that should already get a working initial version. From there adjustments to the downloads-handler would be necessary so that MO2 can handle NXM links.

After ensuring everything works it would be nice to strip unnecessary code. That is a little more work as it would require a considerable amount of testing.

**Comment by rockerbacon** [comment]
I've published a new [release with a prototype](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.0). I don't have much time to work on this project so I'd appreciate if someone could test it a little more for me.

One thing to note is that the latest version I could get working was 2.2.0 with newer versions raising errors related to Visual C++ libraries.

**Comment by rockerbacon** [comment]
First stable version of an MO2 installer for Skyrim was just released, with the latest version of MO2.

For this installer I went with a different approach, doing a complete modding package instead of relying on multiple different installers. This installer includes SKSE, ENB support and does not require any tweaks on Steam.

**Comment by spannerman79** [comment]
You can also use or take a look at [vkBasalt](https://github.com/DadSchoorse/vkBasalt).  It has _limited_ support for the reshade Fx shaders (~ 80%) out of the box.

GamingOnLinux has made [some](https://www.gamingonlinux.com/index.php?module=search&q=vkBasalt) coverage and support to tweak vkBasalt is now part of GOverlay.

**Comment by rockerbacon** [comment]
> You can also use or take a look at [vkBasalt](https://github.com/DadSchoorse/vkBasalt). It has _limited_ support for the reshade Fx shaders (~ 80%) out of the box.
> 
> GamingOnLinux has made [some](https://www.gamingonlinux.com/index.php?module=search&q=vkBasalt) coverage and support to tweak vkBasalt is now part of GOverlay.

My plan is to get ENB working on all games. Currently I've managed to get ENB working for Skyrim and I've applied the same methods for getting it to work to other DX9 Bethesda games.
The problematic part now is getting it to work on the newer DX11 titles.

**Comment by rockerbacon** [comment]
With #28, the MO2 installer now supports all games the Vortex installer does. All that remains now is to update the documentation.

I'll be closing this issue. For further support or suggestions regarding MO2 users and contributors should open specific issues.
