### ISSUE TITLE
Remove dependency on Lutris

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/lutris-skyrimse-installers#182]
The current implementation of the installer relies on Lutris by design. At the beginning this was a great way to get things done faster but as the project was developed and maintained relying too much on Lutris proved to be an obstacle. There are currently two important fixes the project needs which are being held back by Lutris development:

- Using Protontricks alongside an up to date version of Winetricks in order to fix recurring problems with prefix setup, including but not limited to #61 #178 #158 #146 #139
- General problems in Lutris itself after update 5.8 (#175)

A Lutris installer will still be provided but the installer will merely download and execute the independent installer.

This migration is something I've been meaning to do for quite some time but I haven't had the time to work on. I would greatly appreciate help from anyone with bash knowledge and I'll provide full support to anyone wishing to get involved. Requirements and progress will be tracked in a GitHub project.

Feel free to ask questions and leave suggestions in this issue.

**Comment by rockerbacon** [comment]
I've added the `independent-installer` label and created the branch [independent-installer](https://github.com/rockerbacon/lutris-skyrimse-installers/tree/independent-installer).

I'll be opening issues describing tasks when I get home from work. Anyone who can already see things that need to be done is free to open new issues and pull requests.

**Comment by jthistle** [comment]
Hey! I've been just trying to get this to work and share your frustration with Lutris.

What exactly is the reason for dependence on Lutris in the first place? I can only see one thing being the ability to very simply download resources. And also maybe knowing where the game files are kept. But really, this should absolutely be rewritable as a standalone thing.

Have you considered using a more, uh, maintainable language like Python to rewrite this? Not that bash is bad; in fact it's excellent for filesystem-level stuff like this, just that it's quite painful to use.

**Comment by rockerbacon** [comment]
> Hey! I've been just trying to get this to work and share your frustration with Lutris.
> 
> What exactly is the reason for dependence on Lutris in the first place? I can only see one thing being the ability to very simply download resources. And also maybe knowing where the game files are kept. But really, this should absolutely be rewritable as a standalone thing.
> 
> Have you considered using a more, uh, maintainable language like Python to rewrite this? Not that bash is bad; in fact it's excellent for filesystem-level stuff like this, just that it's quite painful to use.

Lutris made a lot of sense when this project was built around Vortex. If you look at the old Vortex installer, it was just one script to create a bunch of symlinks and the Lutris installer.
After Wine got support for Window's VFS, Mod Organizer 2 became a possibility and the thought was that it was easier to build around something that was already made rather than redoing everything from scratch.

Bash was chosen because it is readily available, great for managing the filesystem, integrates with external programs in a relatively clean manner and everything you can run on a terminal can be put directly into a script. That last part was very important for getting things done faster, as the bulk of the work in this project was research and experimentation with the code itself being just for automation.

I'm open to switching technologies if they provide any noticeable benefit but I don't see it as something too important right now.

**Comment by jthistle** [comment]
Cool, thanks for the explanation. FWIW I wouldn't say that Python provides any real benefit over Bash other than maintainability; it was just a suggestion.

**Comment by Leooow** [comment]
@rockerbacon I would like to help but have no idea what I could contribute, any suggestions?

**Comment by rockerbacon** [comment]
> @rockerbacon I would like to help but have no idea what I could contribute, any suggestions?

I'm trying to keep track of everything I think needs to be done through issues. You can filter all issues related to this by using the `label:independent-installer` filter in the search in the issues tab ([quick link for ease](https://github.com/rockerbacon/lutris-skyrimse-installers/issues?q=is%3Aissue+is%3Aopen+label%3Aindependent-installer)).

If you're not comfortable developing, you can always keep an eye on pull requests and test them.

**Comment by Leooow** [comment]
> > @rockerbacon I would like to help but have no idea what I could contribute, any suggestions?
> 
> I'm trying to keep track of everything I think needs to be done through issues. You can filter all issues related to this by using the `label:independent-installer` filter in the search in the issues tab ([quick link for ease](https://github.com/rockerbacon/lutris-skyrimse-installers/issues?q=is%3Aissue+is%3Aopen+label%3Aindependent-installer)).
> 
> If you're not comfortable developing, you can always keep an eye on pull requests and test them.

I'll have a look to see what I can do 👍🏼

**Comment by jthistle** [comment]
@rockerbacon hey, how are you? Just wondering if there's any progress being made on this project :)

**Comment by rockerbacon** [comment]
> @rockerbacon hey, how are you? Just wondering if there's any progress being made on this project :)

I switched jobs recently and things got a little busy. I'm resuming work on the project today.
Apologies for my absence.

**Comment by jthistle** [comment]
No need at all to apologize, nice to see you're back

**Comment by class101** [comment]
I have Vortex latest version 1.3.22 running here without Lutris but on Proton, added as non-Steam game. So far everything is working fine here.

I wrote and saved a little procedure on file for my need in setting up a proton prefix properly with vcrun2019, directx and dotnet48 without the need of winetricks that usually does too much but the Steamworks Shared redistributables instead.

Let me know if anybody interested.

**Comment by kleshas** [comment]
I'd be interested

**Comment by spannerman79** [comment]
I too am getting a bit miffed at how limited Lutris is.  I've been looking more at Q4Wine to handle wine instances.

Yes there is more setup involved but at least I can actually export and import instances easily and very quickly.  Good luck trying to do that with Lutris.

Q4Wine also downloads winetricks _directly_ from `https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks` so its always up to date - another fault with Lutris.  Even though you have selected "use system libs" it still wants to use their packaged winetricks.  PITA.

-----

_Before anyone states that I'm just pushing this (Q4Wine) to dodgy download/install games - feel free to take a look at my actual [Steam Library](https://steamcommunity.com/id/spanner_man/games/?tab=all&sort=name) and take note if I have or have not already have Skyrim on there._

**Comment by class101** [comment]
> I'd be interested

Here it is, tested on Vortex 1.4.8 (latest version as of writing)

https://steamcommunity.com/app/221410/discussions/0/3094509155631896210/

**Comment by class101** [comment]
> I'd be interested

@kleshas 

Here it is, tested on Vortex 1.4.8 (latest version as of writing)

https://steamcommunity.com/app/221410/discussions/0/3094509155631896210/

**Comment by basschaser** [comment]
@rockerbacon Hey, I'm just wondering where you're at with this as I'm potentially interested in contributing.

I was actually attempting to do this for myself already, until I found your Lutris installer. I'm quite capable with bash, but less so with the WINE side of things as I'm not so experienced there. We might be a good match for this project. Let me know.

Btw, thanks for the Lutris installer. It works perfectly for me.

**Comment by marcus-grant** [comment]
Might be interested in helping but a discussion about the best approaches is probably necessary first and I'll start by suggesting ansible might be a good bridge to exiting lutris. It uses declarative YAML files to provision complex systems and perform devops operations way more complex than this and has a familiar syntax to anyone who's used to lutris. Otherwise of course we could just do plain BASH scripts.

Let me know what you think I might just create a new project and take a lot of your current work and see if implementing it in ansible is any easier or more maintainable.

**Comment by spannerman79** [comment]
ansible is more focused on massive automation ie kubernetes.  To the end user (ie gamer) they will only have one instance of TES:Skyrm installed.

**Comment by basschaser** [comment]
@marcus-grant Yeah, I use Ansible on the regular for managing my home server. I don't really feel it's appropriate for this use case though. It's an unnecessary dependency, and would actually make things quite difficult given that this requires a bunch of custom logic that makes Ansible an unrealistic choice without writing a custom module.

I've whipped up something in BASH that is (should be) functional, but it's not properly documented or feature complete yet. It's a bit of an opinionated project, as the current goal is to set things up for the heaviest of mod stacks, so there is no Vortex support because it simply isn't up to the task IMO. If you're just looking for a simple tool that installs MO2 or Vortex, then [Steam Tinker Launch](https://github.com/frostworx/steamtinkerlaunch) might be more appropriate.

If you want to take a look at the project, it can be [found here](https://github.com/basschaser/steamplay-skyrim-tools). Please feel free to open an issue there if you're interested in discussing things further. As I said, it should be functional but I've only tested it on my system so far, so YMMV. Definitely make a backup of anything Skyrim-related you have. It does reuse quite a bit of existing code from this project, so I'm fairly confident that it will work as expected. To install it, simply run the script and follow the menu. To uninstall, just append --uninstall. Also, this has not been tested with the recent SkyrimSE update at all, and probably won't work with it.

**Comment by marcus-grant** [comment]
@basschaser Yeah you're right, I think I'm trying to solve problems with Lutris as a whole, not this project in particular and without the crucial piece to do it, a WINE module for ansible. And yeah I tried the SteamTinkerLauncher and it seems like that already does most of what this is supposed to do, though I'm having trouble getting it to correctly setup the MO2 broker for nexus links, seems to work in Vortex though. I'll check out your project and see if I find anything that might get it more complete after figuring out a reliable way to backup my modded games and restoring them. Something standalone for just setting up game modding from nexus would be nice to have since it's easier to maintain than the 30k+ line bash script in STL (awesome as it is otherwise).

**Comment by basschaser** [comment]
@marcus-grant I completely understand the temptation to do eveything with Ansible, it's a really sweet tool and I'm definitely excited at the prospect of a WINE or SteamPlay module for Ansible. I've noticed that Valve has a couple of Python libraries for Steam already, so those should be helpful. This is definitely something that would catch my interest in the near future. It could absolutely replace Lutris, and the possibilities would be nearly limitless.

Thanks for your interest in the project! I believe what I have is *mostly* complete for the average user, but it does need a bit of work and some proper testing still. Here's what it does so far:
- Finds all available Steam libraries, and locate the game files and prefix (should work for all Fallout and TES games)
- Download the tools into a cache location
- Tracks all files that it installs (for uninstallation)
- Installs the required verbs with Protontricks
- Installs the ProtonPreloader binary, which allows launching the game's MO2 instance from Steam
- Install MO2 and the various runner scripts required for 
- Install LOOT
- Install ENB (but I think I haven't pushed these commits yet)
- Uninstall function that should revert the game instance back to stock (including the prefix)

The only thing the user should have to do is set the game's Proton version to 5.0, and install. (and don't forget to run the game once before installing any mods!)

There are some points that could be addressed off the top of my head:
1) Expansion of the menu system. As of right now it's very basic, just enough to be functional. This could include various switches for tools, MO2 installation location, etc. Could probably use zenity to make it GUI-driven.
2) MO2 links should be working as they're almost 100% carried over from the Lutris scripts in this repo. One pain point I've had with them is that they consistently turn into zombie processes. I've tried some modifications to resolve this, but haven't been successful so far. I would look at the [proton-launcher.sh](https://github.com/basschaser/steamplay-skyrim-tools/blob/master/runners/proton-launcher.sh) script for this, as that's how the nxm-handler is called.
3) I'd like to implement a backup function of the game's executable and DLLs, since Bethesda insists on forcing Creation Club updates and Steam has no way to ignore updates without using Offline Mode.
4) ProtonPreloader may be an unnecessary dependency. It's the only way I've found so far to get Steam to launch MO2 directly so far.
5) I wouldn't mind getting tools such as FNIS and Nemesis installed if possible, as they can be a pain to get the pathing to work correctly with MO2.
5) Testing. I only have Skyrim SE and my Arch gaming rig to test this on, so if you have any other games and configurations that would be exceedingly helpful.
6) Documentation, of course.

I agree with your assessment regarding STL as well, it's a great project but at 30k+ lines it's already a lot to maintain. I generally tend to follow the "do one thing and do it well" philosophy, rather than the monolithic philosophy.

I am going to try and get this project finished off over the next week or two, so if you decide to work on something just let me know so that we aren't both tackling the same problems!

**Comment by frostworx** [comment]
Hi, steamtinkerlaunch author here.
I prefer the "one thing well" philosophy as well, and thoroughly understand what you mean/criticize,
but IMHO steamtinkerlaunch matches that description in this context perfectly, because it is one tool to tweak and tinker with all your steam games. There are not many options to do this in Steam apparently (and let's hope those few remain available), so the only user-friendly option is to have one tool for this one thing. </twocents>

_ps: yeah, ansible ftw ;)_

**Comment by rockerbacon** [comment]
Apologies to everyone for the long absence. Work and college have kept me very busy but I finally found some time and motivation to finalize this migration.

Pre-release [3.0.2](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/3.0.2) is out for anyone interested. Now only a few things remain:
- Making the necessary adjustments to the readme
- Testing more extensively
- A little bit more code for pure Wine support

I expect all future developments to be a lot easier after this update.
