### ISSUE TITLE
Error on install: "Error while installing winetricks"

### ISSUE THREAD

**Issue by Arcstur** [rockerbacon/lutris-skyrimse-installers#194]
I'm trying to install on Lutris 0.5.8.1, Linux Mint 20.
This also happened in Lutris 0.5.7

I can get near to the end of installation, then an erro message appears:
![image](https://user-images.githubusercontent.com/24514392/102147973-6cdf2f00-3e4a-11eb-837e-7986dec0ac20.png)

Early on in the command line while installing, there is this message which I think must be advising the problem:
![image](https://user-images.githubusercontent.com/24514392/102148084-9009de80-3e4a-11eb-98b4-be0ff81e3da2.png)

You are running winetricks-20200412-next, latest upstream is winetricks-20201206!

I don't know what do to really. because if I check "winetricks --version", my system says it is 20201206, which seems to be the latest. Can someone help me, please? Thank you so much.

**Comment by kleshas** [comment]
Here's one way to update winetricks (the issue is lutris uses its own version, not system version that winetricks --self-update works on)

cd "${HOME}/.local/share/lutris/runtime/winetricks"
sudo mv winetricks old_winetricks
sudo wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
sudo chmod +x winetricks
