### ISSUE TITLE
Error every time I try to set mod organizer up for Fallout 4, claims it cannot find the game.

### ISSUE THREAD

**Issue by YouDontCare** [rockerbacon/lutris-skyrimse-installers#260]
Like, the whole thing seems to be working, until the very end when it says it can't find the game. 

But the weird thing is like. [If you look at this pastebin](https://pastebin.com/XnUbKfyz) of the terminal output when trying to run the install -- It apparently says that the install script _can_ see the game, but `find-library-for-appid.sh` is failing to return the information to some other script that would handle it... ? I can't say I know my shellscript, but that's what it looks like to me.

**Things I already attempted:**

1. Moving Fallout 4 to a different Drive so it'd be on a different library folder
1. Selecting the option that says I'm not using steam and then manually punching in my steam wineprefix for the game ID and steam install dir for the game. Craps out in a different way, saying Winetricks failed to install dotnetfx45 (`returned status 67 aborting`)
1. Downloading an older release of the script. Hey, it might have worked. Didn't, but idk.
1. Changing which version of Proton Fallout was using. Made it worse, game wouldn't open anymore.
1. Praying to the machine gods for providence. Didn't work.

Don't know if this is like, an issue with the scripts or if I'm doing something wrong. Idk

**Comment by Alekhine51** [comment]
I'm having a similar issue with Skyrim SE. There does seems to be some problem with the script, but I can't spot it. I've emailed the dev for help with getting everything run locally so I can solve this.

**Comment by juliovco** [comment]
I'm having the same issue with Skyrim SE too.

**Comment by rogovski** [comment]
@YouDontCare @Alekhine51 @juliovco 

in the installer yaml that you download change every reference of 2.8.4-utils to 2.9.0-utils

for example (in the modorganizer2.yml) change:

```
https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-utils/dialog.sh
https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/2.8.4-utils/find-library-for-appid.sh
```

to

```
https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/2.9.0-utils/dialog.sh
https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/2.9.0-utils/find-library-for-appid.sh
```

there is an issue in the 2.8.4 utils release bash scripts where 'return' is being used instead of 'exit'

**Comment by graygrotesque** [comment]
Hey! The installation finally worked fine with the changes in the .yml file, but when I try to start MO2 nothing happens. No error message. The button in lutris turns from "Play" to "Stop" for a few seconds and reverts back to "Play".

it's my first time trying to mod the game in linux since I switched to linux only a few months ago. Sorry if I missed something obvious. :3

**Comment by juliovco** [comment]
Graygrotesque, do you have Skyrim installed with proton 5.0 in steam? I tried many different changes in the installation process, and in one of my tries I had that same result, and if I remember correctly it was the time I tried with Skyrim installed with proton 6.3. If that is your case, I suggest removing MO2, uninstall Skyrim, change proton version, then reinstall Skyrim, open the game once and close, reinstall MO2.
Also, even though I did'n buy the Anniversary upgrade, my game was updated to version 1.6.342, so the skse64 didn't work. I had to download another version of skse64, from [https://skse.silverlock.org](https://skse.silverlock.org/) If that also is your case, you can download the right skse64 and use it during the MO2 installation, or change the target in the yml for that too.

**Comment by graygrotesque** [comment]
Hey, thanks for the fast answer! :)

It's Fallout 4 in my case and I have installed it with Proton 6.3.8, then installed MO2 with this installer here (modified the 2.8.4-utils lines). Is this procedure with Proton 5.0 working with FO4, too or only with Skyrim?

**Comment by juliovco** [comment]
Sorry, I forgot to ask which game it was. I don't have FO4, but there is a step in the installation in which it asks you if the game is installed trough steam, and using proton 5.0, and if you started the game at least once.
As I said, I tried a lot of changes, and in one of them that same thing happened, I would start MO2 but a few seconds later it would stop with no error message. But I'm not totally sure what I did then. I remember now I also tried updating MO2 (and once I tried downloading the most recent version of MO2 from nexus and using it during installation), it might have been then that MO2 didn't start any more.
Mine is working perfectly now. What I did was follow mostly everything as was told. I only changed dialog.sh and find-library-for-appid.sh to version 2.9.0 and skse64, but that one doesn't apply to you since you'll be using f4se for FO4. And I'm keeping it not updated, using the version installed by the yml.

**Comment by rockerbacon** [comment]
I recommend everyone still affected by this issue to try the newer pre-release [3.0.2](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/3.0.2). Be mindful this newer release does not install through Lutris, instructions are in the release page.

**Comment by graygrotesque** [comment]
Hey there,

I installed the version 3.0.2 but it wouldn't start after I choose the game and the installer ended. :/
But it worked with installing the lutris version with the modified .yml and installing the game with Proton 5! :D I even got it to react to nxm links. Thanks for the help and for the work on this project here!

Now I have to figure out how all the modding works in linux. :D
