### ISSUE TITLE
Feature request: Custom Proton support

### ISSUE THREAD

**Issue by ajventer** [rockerbacon/lutris-skyrimse-installers#33]
The current protonlauncher.sh doesn't seem to be able to launch custom proton versions such Proton-GE. Even when installed into steam's compatibilitytools.d directoy and selectable in the steam client, adding the version into the run.sh script causes it to break. It looks for it in the common directory,  copying the custom proton there it still cannot find it.

Several bethesda games, notably FO4 work significantly better with GE versions of Proton than stock versions - but currently this version cannot be used with these MO2 installers.

**Comment by rockerbacon** [comment]
Currently, the option `--protonver` can passed to `proton-launcher.sh` in order to specify which version of proton to use. There are two issues with using this option in this context:

- The current matching pattern requires the custom version to be in a directory whose name is prefixed with "Proton ";
- The forwarding of arguments from Lutris to `proton-launcher.sh` is only implemeted in `2.4.0` and not present in any stable release;

**Comment by rockerbacon** [comment]
Added in #35

**Comment by rockerbacon** [comment]
Released in [2.5.0](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.5.0).
Custom proton versions should be specified using the arguments setting in Lutris. In order to see all options available use the following command:

```bash
$HOME/.local/share/modorganizer2/proton-launcher.sh --help
```

**Comment by ajventer** [comment]
With 2.6.0 this doesn't work yet:

 Could not find proton version matching '5.8-GE-1-MF' in directory '/home/metalpoetza/.steam/steam/steamapps/common/'
You can override the version with parameters now but it doesnt' find custom builds.
That's because the PATH for custom builds it's $HOME/.steam/steam/compatibilitytools.d/{PROTONDIR} 

in my case:
$HOME/.steam/steam/compatibilitytools.d/{Proton-5.8-GE-1-MF

So the protonver search should include compatibilitytools.d in it's search path as well in order to provide this feature.
