### ISSUE TITLE
Lutris-Wrapper Process disconnects Bluetooth Devices / Doesnt terminate

### ISSUE THREAD

**Issue by klapperking** [rockerbacon/lutris-skyrimse-installers#47]
When starting MO2 through Lutris, the starting lutris-wrapper process disconnects bluetooth devices. 

Additionally, when closing MO2 that process doesnt terminate.

**Comment by rockerbacon** [comment]
Does this happen consistently every time?

I noticed that Proton sometimes has trouble terminating frozen processes, probably because it always sends a "SIGTERM" and never a "SIGKILL" and since the process is frozen it can't handle a graceful termination. If you can confirm it only happens when things freeze then there are things I might be able to do to improve this. If it happens every time, I will need to investigate your specific case a little more.

If you are having trouble with bluetooth audio devices: the script resets Pulseaudio before starting in order to clear Pulseaudio's buffer, which helps reduce audio crackling in-game. You can disable this in Lutris:

1. Right click Mod Organizer > Configure > Game Options;
2. Add "--keep-pulse" to Arguments and click "Save";

Other than audio there's nothing the scripts touch that could affect bluetooth.

**Comment by klapperking** [comment]
it was indeed only audio devices - fixed.
Thank you very much!
