### ISSUE TITLE
Crash right after the Vortex installer finishes

### ISSUE THREAD

**Issue by ptkato** [rockerbacon/lutris-skyrimse-installers#5]
![image](https://user-images.githubusercontent.com/10677806/62405855-44b69f00-b579-11e9-8aee-7d2a7cc25bd7.png)

This happens at the "Vortex Setup", I can't really tell if the actual Vortex installation finishes, but it crashes and leaves the lutris installer hanging "waiting on children". I guess it does finish installing, because the crash is in the Vortex.exe, and not in the installer executable.

**Comment by rockerbacon** [comment]
If you're using the version on lutris.net, it is outdated because the update is still waiting for moderation. You should download [vortex.yml from the latest release](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/1.8) and install it with the command:
```
lutris -i <path to vortex.yml>
```
If you find you still have the issue confirm you're using at least Lutris 0.5.2.2 with the command:
```
lutris -v
```
