### ISSUE TITLE
Unable to apply fix for broken audio

### ISSUE THREAD

**Issue by 7hr08ik** [rockerbacon/lutris-skyrimse-installers#82]
Hey, 

Quickly. THANK YOU FOR THIS!

OK, so theres this random bug, (according to ProtonDB, its a bug with Proton itself) that causes strange audio behaviour. For some, no left, for others no NPC sounds. For me, randomly the audio will just cut out. At random intervals

`WINEDLLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=90 %command%`

This is the fix, for Steam Launch Options. I know you've implemented the first part. But I still have  weird audio issues through your setup. 

I know the launch options in Steam have no effect, as this will launch the game with its own options. How can I set PulaseAudio latency?

**Comment by spannerman79** [comment]
Personally I use GloriousEggroll fork of Proton.  [This one](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.8-GE-2-MF) currently in specific that applies those wine overrides by default.

Or you could use [protonfixes](https://github.com/simons-public/protonfixes) to apply those needed changes.

**Comment by rockerbacon** [comment]
These values are called environment variables. There are two ways to specify custom environment variables in Lutris:

1. The builtin feature in Lutris: Right click on Mod Organizer 2 > Configure > System Options > Environment Variables;
2. Through arguments to the script: Right click on Mod Organizer 2 > Configure > Game Options > Arguments > Add the argument `-e 'ENVIRONMENT_VARIABLE=value'`;

I will leave this open until PULSE_LATENCY_MSEC is set by default in the installer.

Note that just these two environment variables might not be enough. Many people have reported that the only way to get perfect audio in Skyrim SE and Fallout 4 is by compiling FAudio with ffmpeg codecs and using these instead of the FAudio libraries provided by Proton.

**Comment by 7hr08ik** [comment]
spannerman79 - Thank you. I keep forgetting to try out GE-proton, never really had a reason to look at it until now.

rockerbacon - See I know theres the option in lutris to add these, but i figured as lutris is running your run.sh, it wouldnt do anything. So I didnt even try that.
As for Faudio. I have never done a single thing with it, I know it exists, seen it in some lists, but thats about it.

Im gonna give all of these options a try, and I will report back. Might be a couple of days though. Thank you both

**Comment by spannerman79** [comment]
> As for Faudio. I have never done a single thing with it,

faudio patches are part of GE's fork of Proton. As well as a couple of other things (mf, etc).  

As you can see on my reports on protondb first [without](https://www.protondb.com/app/489830#pUiuehhfo) using GE's fork and later [with](https://www.protondb.com/app/489830#794VANDBz).

**Comment by 7hr08ik** [comment]
Hey,

So, Proton-GE pretty damn cool. But I still have random drops of only half of the games sounds. Weapons, NPCs, Magic.

In lutris settings (both system and game) ticking Pulse latency does not help.

But adding -e "ENV....=90' seems to be working. Gonna guess because Lutris only does 60, but I don't know why
